POST http://127.0.0.1:5000/add HTTP/1.1
Content-Type: application/json

{
        "server_name" : "Africa",
        "max_user" : 20000,
        "wallet" : 0,
        "unit" : "SAD",
        "address" : "Africa"
}


GET http://127.0.0.1:5000/getServers HTTP/1.1


GET http://127.0.0.1:5000/getServersByid/3 HTTP/1.1


DELETE http://127.0.0.1:5000/delServersByid/9 HTTP/1.1


PATCH http://127.0.0.1:5000/updateServer HTTP/1.1
Content-Type: application/json

{
        "id" : 300,
        "server_name" : "Asia",
        "max_user" : 20000,
        "wallet" : 0,
        "unit" : "SGD",
        "address" : "Asia"
}
